### ISSUE TITLE
Every time Strenght -1 Magic +1

### ISSUE THREAD

**Issue by ElInvocador2** [Wehavecookies56/Kingdom-Keys#30]
It seems that every time I enter the game my strength is reduced to 1 and my Magic increases by 1, is there a solution?
(https://user-images.githubusercontent.com/112722912/188210108-401fc0cc-bcbd-42db-b326-155352a34f49.png)

**Comment by Wehavecookies56** [comment]
I'm guessing this is on a world created before 2.1.6.3, it seems there is a bug with how I implemented the new stat system with new worlds, I'll find a fix for it but for now if you send your .dat file, from the playerdata folder in your world folder, I'll manually edit it to fix it

**Comment by ElInvocador2** [comment]
Thank you very much for the answer, I'll pass you the file and that of a friend to whom apparently it's the opposite, it increases its strength and decreases its magic.
I upload the files by mediafire since it does not let me upload them directly.
My file: https://www.mediafire.com/file/tr8zjej9doma9rz/9c4bc0e3-b4a5-3bfb-8c76-6cbcd602467f.dat/file
My friend's file: https://www.mediafire.com/file/njkuwzk5qjuqw61/0f383e25-04bb-37bc-b1e0-da80b3cdd126.dat/file
Thank you very much for your time.

**Comment by Wehavecookies56** [comment]
Oh yeah I see it only allows certain file types, zip works at least.

Hopefully if I did this right they should be fixed now with these
[playerdata.zip](https://github.com/Wehavecookies56/Kingdom-Keys/files/9483211/playerdata.zip)

**Comment by ElInvocador2** [comment]
Hello again, now my problem is that my strength doesn't increase with the keyblade, it stays the same.
And now my friend every time he enter the game, he obtain +1 strength.

**Comment by Wehavecookies56** [comment]
Is that value showing correctly in the keyblade tooltip? The status screen shows it without the keyblade stats added.
I found the cause of that bug as well in my commit, it will happen on the current version if you sacrifice warrior tomorrow I'll get a build up with the fix so temp fix would be to use /kingdomkeys choice <choice> <sacrifice> and set the sacrifice to one of the others for now.

**Comment by ElInvocador2** [comment]
I still have the problem, i choose a keyblade and the strenght is the same, i tried to set level 1 my character, choose warrior and sacrifice the mystic and still have the problem, and my friend still have the first issue +1 strength and -1 magic 
(https://user-images.githubusercontent.com/112722912/188286981-80b8a3b2-e116-4773-a247-213f82378a81.png)
and and these are my stats (keyblade include)
(https://user-images.githubusercontent.com/112722912/188287020-5146c172-ffc5-4a21-ba2f-eb060f0dc98e.png)

**Comment by Wehavecookies56** [comment]
Yeah sorry I should've said same issue with warrior being the choice basically I messed up with the check so that'll be fixed in the build tomorrow. If you look at the tooltip of the keyblade you have it will be your strength + the keyblade's strength but in that gui it will just show your strength without the keyblade so the keyblade is effecting the damage.

**Comment by ElInvocador2** [comment]
Oh thank you so much, now the only problem we have is that my friend still have the issue +1 strength -1 magic

**Comment by ElInvocador2** [comment]
And... now i have the same issue of my friend and apparently my friend recover all limit bar when he dies
